workspace:
  base: /go
  path: src/github.com/uswitch/elastic-log-lag

pipeline:
  build:
    image: golang:1.19
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/elastic-log-lag

  docker-branch:
    image: plugins/docker
    repo: quay.io/uswitch/elastic-log-lag
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/elastic-log-lag
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    when:
      event: push
      branch: master

  docker-tagged:
    image: plugins/docker
    repo: quay.io/uswitch/elastic-log-lag
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
